### ISSUE TITLE
Trying to get error messages out as a string that i can display.

### ISSUE THREAD

**Issue by bltomato** [groue/GRValidation#1]
Hi,

I am on Xcode 7.0 and swift 2 and for the life of me, i can't figure out how to get just the validation error "message" so I can display it elsewhere when using a complex validation. 

This is my validation struct:

---

import Validation

struct PersonValidationModel : Validable {

```
var firstName: String?
var lastName: String?

mutating func validate() -> Bool {

    do
    {
        try ValidationPlan()
            .append {
                // firstName should not be empty after whitespace trimming:
                let nameValidation = ValidationTrim() >>> ValidationStringLength(minimum: 1)
                firstName = try validate(
                    property: "First Name",
                    with: firstName >>> nameValidation)
            }
            .append {
                // lastName should not be empty after whitespace trimming:
                let lastNameValidation = ValidationTrim() >>> ValidationStringLength(minimum: 1)
                lastName = try validate(
                    property: "Last Name",
                    with: lastName >>> lastNameValidation)

            }
            .validate()

            return true

    } catch {

        let v = error as! ValidationError

        //somehow get error messages as a string or array of strings??????

      //i would like to get a string here that would contain: "First Name should not be empty." if I left the first name field empty.


        return false
    }

}
```

---- and this is how i call it ---

```
    let firstNameText = firstNameField.stringValue
    let lastNameText = lastNameField.stringValue

    var person = PersonValidationModel(firstName: firstNameText, lastName: lastNameText)

    if person.validate() {
        print("was valid")
        saveRecord()
    }
```

When I run it and remove strings from those text fields, I can see the error if I send the let var "v" to the console log:

Invalid TossSheet.PersonValidationModel(firstName: Optional(""), lastName: Optional("Otero")): First Name should not be empty.

I don't know what to cal to just retrieve the "error message" message:

"First Name should not be empty."

or 

"First Name should not be empty." and "Last Name should not be empty." 

if I leave both fields empty.

and when I just try to run the validation without a do/ try / catch i get an error:

FormControllerValidation.swift:12:13: Errors thrown from here are not handled

FormControllerValidation.swift:12:17: Call can throw, but the error is not handled

**Comment by groue** [comment]
Hello @bltomato,

You have two questions:

> I don't know what to cal to just retrieve the "error message" message "First Name should not be empty."

This feature is not supported today, because I did not add localization support yet (so that one would get "Le prénom est manquant" or "Primer nombre no debe estar vacío").

So this is a feature request :-)

> and when I just try to run the validation without a do/ try / catch i get an error:

Yes, Swift 2 requires errors to be handled. That's how it is with Swift:

``` swift
// This function is not declared `throws`, and thus it MUST handle absolutely all errors.
mutating func validate() -> Bool {
    do {
       try ValidationPlan()...validate()
    } catch let error as ValidationError {
        // ValidationError
    } catch {
        // Mandatory default case
        fatalError("Unexpected error: \(error)")
    }
}
```

**Comment by bltomato** [comment]
Thank you. I won't be able to test and try this until the morning though! will close after that.

**Comment by groue** [comment]
OK. If you don't care about localization, it won't be too difficult to add the method that return the short description anyway. I'm waiting for you!

**Comment by bltomato** [comment]
for me, localisation would not be as important right now as I am at the start my project.
Having a method to call and return the "error description" would be fantastic though!

**Comment by bltomato** [comment]
Thank you for the sample code. It helped me out. I think this will be good for now. Tonight I will write up a feature request for grabbing the "missing phrase" for the respective fields. thank you very much!

**Comment by groue** [comment]
OK. I'm still thinking about it in a background task of my mind. Stay tuned :-)
